server:
    port: 8083

spring:
    application:
        name: transaction_service
    datasource:
        #postgres local database
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/test_transaction}
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASS:postgres1}
    jpa:
        hibernate:
            ddl-auto: update

    output:
        ansi:
            enabled: ALWAYS

logging:
    level:
        com:
            skillstorm: debug

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
        
    
