server:
    port: 8083

spring:
    application:
        name: transaction_service
    datasource:
        #postgres local database
        url: jdbc:postgresql://localhost:5432/test_transaction
        username: postgres
        password: postgres1

    output:
        ansi:
            enabled: ALWAYS

# eureka:
#     client:
#         serviceUrl:
#             defaultZone: http://localhost:8761/eureka/
    
